-- Copyright The OpenTelemetry Authors
-- SPDX-License-Identifier: Apache-2.0

CREATE USER otelu WITH PASSWORD 'otelp';

-- Accounting Service: create a schema
CREATE SCHEMA accounting;
GRANT USAGE ON SCHEMA accounting TO otelu;

-- Accounting Service: create tables
CREATE TABLE accounting."order" (
    order_id TEXT PRIMARY KEY
);

CREATE TABLE accounting.shipping (
    shipping_tracking_id TEXT PRIMARY KEY,
    shipping_cost_currency_code TEXT NOT NULL,
    shipping_cost_units BIGINT NOT NULL,
    shipping_cost_nanos INT NOT NULL,
    street_address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    zip_code TEXT,
    order_id TEXT NOT NULL,
    FOREIGN KEY (order_id) REFERENCES accounting."order"(order_id) ON DELETE CASCADE
);

CREATE TABLE accounting.orderitem (
    item_cost_currency_code TEXT NOT NULL,
    item_cost_units BIGINT NOT NULL,
    item_cost_nanos INT NOT NULL,
    product_id TEXT NOT NULL,
    quantity INT NOT NULL,
    order_id TEXT NOT NULL,
    PRIMARY KEY (order_id, product_id),
    FOREIGN KEY (order_id) REFERENCES accounting."order"(order_id) ON DELETE CASCADE
);

-- Accounting Service: grant permission to schema
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA accounting TO otelu;

-- Product Review Service: create a schema
CREATE SCHEMA reviews;
GRANT USAGE ON SCHEMA reviews TO otelu;

-- Product Review Service: create tables
CREATE TABLE reviews.productreviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(16) NOT NULL,
    username VARCHAR(64) NOT NULL,
    description VARCHAR(1024),
    score NUMERIC(2,1) NOT NULL
);

-- Product Review Service: create index for product_id lookups
CREATE INDEX product_id_index ON reviews.productreviews (product_id);

-- Product Review Service: grant permission to schema
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA reviews TO otelu;

-- Product Review Service:  add product review data
INSERT INTO reviews.productreviews (product_id, username, description, score)
VALUES
    ('OLJCESPC7Z', 'stylebymia', 'Soft, warm, and polished. This cashmere knit layers beautifully under coats and still looks refined on its own.', '4.7'),
    ('OLJCESPC7Z', 'wardrobeedit', 'The fit is flattering without feeling tight. Premium hand feel and great shape retention after wash.', '4.5'),
    ('OLJCESPC7Z', 'minimallooks', 'A timeless piece for everyday styling. Sleeve length is perfect and the neckline sits cleanly.', '4.3'),
    ('OLJCESPC7Z', 'citycloset', 'Love the silhouette and texture. It works with tailored trousers and denim alike.', '4.6'),
    ('OLJCESPC7Z', 'julescurates', 'Color tone is elegant and easy to pair. Exactly the elevated staple I wanted.', '4.4'),

    ('66VCHSJNUP', 'runwaydiary', 'This denim jacket has a structured cut that instantly elevates casual outfits. Great stitching details.', '4.8'),
    ('66VCHSJNUP', 'dailydrape', 'Perfect weight for transitional weather and very easy to style. Looks premium in person.', '4.6'),
    ('66VCHSJNUP', 'closetjournal', 'Strong shape through the shoulders and clean hardware. A versatile wardrobe anchor.', '4.5'),
    ('66VCHSJNUP', 'streettailor', 'Really impressed by the construction quality. The cropped length pairs well with high-waist pants.', '4.7'),
    ('66VCHSJNUP', 'lookbooklane', 'Comfortable fit with a modern line. A confident everyday outerwear choice.', '4.5'),

    ('1YMWWN1N4O', 'knitedit', 'Beautiful merino cardigan that feels light but warm. The drape is clean and sophisticated.', '4.7'),
    ('1YMWWN1N4O', 'softlayers', 'Buttons and finishing are high quality. Great for office layering and weekend looks.', '4.6'),
    ('1YMWWN1N4O', 'ateliernotes', 'The shape is polished and easy to tuck or wear open. Excellent knit density.', '4.4'),
    ('1YMWWN1N4O', 'modemuse', 'A refined classic that goes with everything. Very comfortable against the skin.', '4.8'),
    ('1YMWWN1N4O', 'capsuleguide', 'Reliable staple for a capsule wardrobe. Holds form well through repeated wear.', '4.5'),

    ('L9ECAV7KIM', 'silkroute', 'This satin shirt has a luxe sheen and a flattering silhouette. Ideal for evening looks.', '4.7'),
    ('L9ECAV7KIM', 'worktowine', 'Great from desk to dinner. The fabric moves nicely and the collar keeps its shape.', '4.5'),
    ('L9ECAV7KIM', 'tailoredtouch', 'Elegant finish and smooth feel without being overly shiny. Very wearable.', '4.4'),
    ('L9ECAV7KIM', 'wardrobecraft', 'Looks premium and feels breathable. Sleeves are nicely proportioned.', '4.6'),
    ('L9ECAV7KIM', 'editbynoa', 'An effortless statement top. Easy to dress up with jewelry or keep minimal.', '4.5'),

    ('2ZYFJ3GM2N', 'citytailoring', 'This tailored blazer is crisp and modern. The structure is strong yet comfortable.', '4.8'),
    ('2ZYFJ3GM2N', 'lineandform', 'Excellent cut through shoulders and waist. Instantly sharpens any outfit.', '4.7'),
    ('2ZYFJ3GM2N', 'fashionledger', 'Great fabric weight and clean lapel roll. Professional and stylish at once.', '4.5'),
    ('2ZYFJ3GM2N', 'seasonlessfit', 'A truly versatile blazer that works year-round. Premium feel for the price.', '4.6'),
    ('2ZYFJ3GM2N', 'minimalwardrobe', 'Beautiful proportions and subtle detailing. One of my most-worn pieces.', '4.7'),

    ('0PUK6V6EV0', 'pantprofile', 'These wide-leg trousers drape perfectly and create a sleek long line. Very flattering fit.', '4.7'),
    ('0PUK6V6EV0', 'smartcasuals', 'Comfortable waistband and excellent tailoring. Works for both work and weekends.', '4.6'),
    ('0PUK6V6EV0', 'clothescraft', 'Fabric quality is impressive and movement is effortless. Looks high-end.', '4.5'),
    ('0PUK6V6EV0', 'neatlines', 'Length and volume are balanced beautifully. Pairs well with fitted knits.', '4.4'),
    ('0PUK6V6EV0', 'urbanatelier', 'A wardrobe essential with a contemporary silhouette. Great value and finish.', '4.6'),

    ('LS4PSXUNUM', 'bootjournal', 'These leather ankle boots are comfortable from day one and look incredibly polished.', '4.8'),
    ('LS4PSXUNUM', 'strideedit', 'Solid construction with a sleek profile. Easy to wear all day in the city.', '4.6'),
    ('LS4PSXUNUM', 'stylewalks', 'The leather quality feels premium and the heel height is practical.', '4.5'),
    ('LS4PSXUNUM', 'capsulefootwear', 'Versatile with dresses, denim, and tailored pants. A dependable seasonal staple.', '4.7'),
    ('LS4PSXUNUM', 'modeonmove', 'Excellent fit and refined shape. These elevate every outfit.', '4.6'),

    ('9SIQT8TOJO', 'coatculture', 'The trench coat is beautifully tailored with a timeless silhouette. Instant sophistication.', '4.9'),
    ('9SIQT8TOJO', 'outerwearedit', 'Perfect weight for spring and autumn. The belt and storm flap details are excellent.', '4.8'),
    ('9SIQT8TOJO', 'runwayready', 'Sharp lines and premium fabric give this coat a luxury feel. Worth every cent.', '4.7'),
    ('9SIQT8TOJO', 'cityuniform', 'A classic trench done right. It layers cleanly over both formal and casual looks.', '4.8'),
    ('9SIQT8TOJO', 'londonlook', 'Great craftsmanship and fit. The most complimented piece in my closet right now.', '4.9'),

    ('6E92ZMYYFZ', 'dressjournal', 'This midi dress is elegant and comfortable with a flattering, movement-friendly cut.', '4.8'),
    ('6E92ZMYYFZ', 'eventedit', 'Perfect for dinners and daytime events alike. Fabric falls beautifully.', '4.7'),
    ('6E92ZMYYFZ', 'simplechic', 'Minimal design with refined finishing. Easy to style up or down.', '4.6'),
    ('6E92ZMYYFZ', 'curatedcloset', 'Great fit through the waist and shoulders. Feels elevated and effortless.', '4.8'),
    ('6E92ZMYYFZ', 'styleoccasion', 'A versatile statement dress with clean lines and premium feel.', '4.7'),

    ('HQTGWGPNH4', 'carryedit', 'This tote bag is spacious, structured, and refined. Perfect for work and travel days.', '4.7'),
    ('HQTGWGPNH4', 'bagnotes', 'Great material quality with practical interior space. Looks sleek without being bulky.', '4.6'),
    ('HQTGWGPNH4', 'dailycarry', 'Comfortable straps and thoughtful shape. Holds essentials and still feels polished.', '4.5'),
    ('HQTGWGPNH4', 'modernminimal', 'A clean, premium tote that matches nearly everything in my wardrobe.', '4.7'),
    ('HQTGWGPNH4', 'commutestyle', 'Stylish and functional in equal parts. Ideal everyday bag for a streamlined look.', '4.6');

-- Product Catalog Service: create a schema
CREATE SCHEMA catalog;
GRANT USAGE ON SCHEMA catalog TO otelu;

-- Product Catalog Service: create tables
CREATE TABLE catalog.products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    picture TEXT,
    price_currency_code TEXT NOT NULL,
    price_units BIGINT NOT NULL,
    price_nanos INT NOT NULL,
    categories TEXT
);

-- Product Catalog Service: grant permission to schema
GRANT SELECT ON ALL TABLES IN SCHEMA catalog TO otelu;

-- Product Catalog Service: add product data
INSERT INTO catalog.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories)
VALUES
    ('OLJCESPC7Z', 'Cashmere Knit Sweater', 'Ultra-soft knit sweater designed for elevated everyday wear. A timeless silhouette that layers effortlessly through every season.', 'ensemble-cashmere-knit.svg', 'USD', 129, 0, 'knitwear,tops'),
    ('66VCHSJNUP', 'Structured Denim Jacket', 'Modern cropped denim jacket with clean seams and a tailored shape. Designed to pair with dresses, trousers, or your favorite denim set.', 'ensemble-denim-jacket.svg', 'USD', 169, 0, 'outerwear,denim'),
    ('1YMWWN1N4O', 'Merino Cardigan', 'Fine merino cardigan with a polished drape and refined finishing. A lightweight layer for workdays, weekends, and travel.', 'ensemble-merino-cardigan.svg', 'USD', 119, 0, 'knitwear,layering'),
    ('L9ECAV7KIM', 'Satin Shirt', 'Fluid satin shirt with a subtle sheen and relaxed tailoring. Crafted for effortless day-to-evening styling.', 'ensemble-satin-shirt.svg', 'USD', 99, 0, 'tops,occasion'),
    ('2ZYFJ3GM2N', 'Tailored Blazer', 'Single-breasted blazer with sharp lines and versatile structure. A wardrobe foundation that instantly elevates any look.', 'ensemble-tailored-blazer.svg', 'USD', 219, 0, 'outerwear,tailoring'),
    ('0PUK6V6EV0', 'Wide-Leg Trousers', 'High-waisted wide-leg trousers cut for movement and clean proportion. Designed to pair seamlessly with fitted knits and structured tops.', 'ensemble-wide-leg-trouser.svg', 'USD', 109, 0, 'bottoms,tailoring'),
    ('LS4PSXUNUM', 'Leather Ankle Boots', 'Refined ankle boots in smooth leather with a comfortable block heel. Built for all-day wear with a sleek city profile.', 'ensemble-leather-boot.svg', 'USD', 189, 0, 'footwear,boots'),
    ('9SIQT8TOJO', 'Classic Trench Coat', 'Signature trench coat with a belt-defined waist and timeless detailing. Lightweight protection and instant polish for transitional weather.', 'ensemble-trench-coat.svg', 'USD', 289, 0, 'outerwear,coats'),
    ('6E92ZMYYFZ', 'Midi Dress', 'Elegant midi dress with a graceful line and versatile fit. Ideal for events, dinners, and elevated daily wear.', 'ensemble-midi-dress.svg', 'USD', 149, 0, 'dresses,occasion'),
    ('HQTGWGPNH4', 'Everyday Tote Bag', 'Structured tote bag designed to carry essentials with ease. Minimal, durable, and polished for workdays and weekends.', 'ensemble-tote-bag.svg', 'USD', 139, 0, 'accessories,bags');
